apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- include "spring.labels" . }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}  
  replicas: {{ .Values.replicaCount }} 
  template: 
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: spring-music
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort}}
