apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-srv
spec:
  type: {{ if eq .Values.env "local" }}{{ .Values.service.typeLocal }}{{ else }}{{ .Values.service.typeOther -}}
        {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
