apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    namespace: argocd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app : {{ .Chart.Name }}
    spec:	
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: ENV
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
